# Generated by Django 4.2.21 on 2025-05-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USer',
        ),
    ]
