# Generated by Django 4.2.21 on 2025-06-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_items_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='items_ordered',
            field=models.ManyToManyField(blank=True, to='store.cartitem'),
        ),
    ]
