# Generated by Django 4.2.21 on 2025-06-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_order_items_ordered_order_items_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_ordered',
        ),
    ]
