# Generated by Django 4.2.21 on 2025-06-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_order_items_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_ordered',
            field=models.ManyToManyField(blank=True, to='store.cartitem'),
        ),
    ]
